version: '3.8'

services:
  frontend:
    image: todo-frontend:latest
    ports:
      - "3000:3000"
    networks:
      - todo-app-network

  backend:
    image: todo-backend:latest
    ports:
      - "8000:8000"
    networks:
      - todo-app-network

networks:
  todo-app-network:
    driver: bridge
